### ISSUE TITLE
改良建议

### ISSUE THREAD

**Issue by hdg8087** [sethyuan/logseq-plugin-media-ts#1]
感谢开发插件，解决了期待已久的需求。不过有几个问题啊：
【1】视频能不能另开一个页面？有时候页面内容稍长一点，视频和笔记之间跳转的话，就得上下拉动页面。
【2】我如果想要视频某个时间点，是要手动输入吗？能不能像ob的时间戳插件一样，点击视频，就自动形成时间戳？
十分感谢！

**Comment by sethyuan** [comment]
我先来回答第2点吧，如果是B站视频的话由于安全限制，没办法直接拿到它的播放状态，只能手动输入；如果是video或audio标签的话（无论播放是不是本地视频）都可以在插入时间戳时自动获取到当前时间点。可以参看README中的动图。

关于第1点，这个目前还做不到。视频可以打开到右侧边栏，但是这样的话主内容区有一个播放器，右侧边栏也有一个播放器，时间戳就无法知道它对应的是哪个播放器了。这块我再想一下。

**Comment by hdg8087** [comment]
嗯，您这个用的是RR youtube的时间戳模式，也挺好。
不过我用了几种时间戳方案，感觉ob的时间戳插件，在操作流程方面更顺手。

**Comment by hdg8087** [comment]
另外，您有没有开发 块间有序列表 的打算？
如同RE这样的效果。
这个功能的确是很多人的刚需，不明白为什么log不做
![Uploading 79731bfbc91cd012d89981784dd4232.png…]()

**Comment by sethyuan** [comment]
@hdg8087 我也觉得是个挺有用的功能，不过我没用过RE，它是怎么控制序号的样式的，用户自己选，还是默认的？

**Comment by sethyuan** [comment]
@hdg8087 回到正题来😂 ，关于如何追踪要控制的播放器，我想是否可以这样设计——用户给要追踪的视频块手动加一个块属性`media-track:: 1`，这样在插入时间戳或者点击时间戳跳转时就可以判断是否有被追踪的播放器，如有就优选采用，如有多个，就采用最后一个（也适用于左右两边都有的情况，也就是优选右侧边栏的）。这样就可以支持如下场景了：

- 用户shift+click视频所在块将其打开在右侧边栏，这样就可以在看视频的同时记笔记
- 标记视频块为追踪
- 在正文区域采用快捷键或 `/` 插入时间戳时是针对被追踪的视频的
- 点击时间戳也是针对右侧边栏被追踪的视频的

**Comment by hdg8087** [comment]
RE的有有序列表样式，是用户自己选的。
如果样式不好做，弄一个样式也可以啊。有比没有强太多。

RE有很多功能都比较好，只是太不稳定。
比如还有：库间页面双链等等。你可以试用一下。

时间戳的问题，我觉得ob插件的流程比较顺手表现在：
左侧做笔记、右侧开视频。
碰到视频中要做笔记的地方，在右侧点的一个按钮上点一下，左侧的光标处就有了时间戳。
一键了事，比较简单。

技术问题我不太懂。能少一些流程自然是首要的原则。

**Comment by hdg8087** [comment]
您是开发者？还是大佬用户呀？

**Comment by sethyuan** [comment]
> 您是开发者？还是大佬用户呀？

我不是Logseq团队的，只是凭喜好做一些插件，解决我的一些痛点，如果能够顺便再帮助到别人那就更好了。

**Comment by sethyuan** [comment]
@hdg8087 刚发了个新版本，现在支持捕获右侧边栏视频的时间戳了。详见README动图，我追加了一个上去。

**Comment by huaoguo** [comment]
> @hdg8087 刚发了个新版本，现在支持捕获右侧边栏视频的时间戳了。详见README动图，我追加了一个上去。

请问捕获侧边栏视频时间戳支持 B 站视频吗？
另外，怎么把视频放到右侧边栏播放呢？

**Comment by sethyuan** [comment]
@huaoguo，

1. shift点击视频块的那个点就可以在右侧边栏打开了，是Logseq的通用操作。
2. B站的嵌入被sandbox了，无法拿到时间戳。

**Comment by huaoguo** [comment]
> @huaoguo，
> 
> 1. shift点击视频块的那个点就可以在右侧边栏打开了，是Logseq的通用操作。
> 2. B站的嵌入被sandbox了，无法拿到时间戳。

谢谢大佬回复~
2. 那 obsidian 的插件咋搞的...
