### ISSUE TITLE
m4v video extension support missing

### ISSUE THREAD

**Issue by nomadhermit** [sethyuan/logseq-plugin-media-ts#10]
Great plugin to fill in gap of core Logseq when it comes to media time-stamping for notes.

When a try "Convert to media renderer" on video asset with "m4v" extension I get "No media", though video plays fine if I use hiccup syntax to embed in a block.

looking at your code it appears m4v extension is missing from video extension list
`const VideoExts = new Set(["mp4", "mov", "mpg", "mpeg", "webm", "ogv", "avi"])`

where as m4a (audio) is included
`const AudioExts = new Set(["mp3", "m4a", "wav", "ogg"])
`

**Comment by sethyuan** [comment]
I added `m4v` to the extension list and published a new version, but I'm not sure if it can be played natively, can you give it a try?

**Comment by nomadhermit** [comment]
just tested after upgrading your latest version.   I can confirm m4v extension is now recognized. Video renders fine natively.
