### ISSUE TITLE
观看视频的同时记录笔记 功能在 logseq0.65失效

### ISSUE THREAD

**Issue by JiangLongLiu** [sethyuan/logseq-plugin-media-ts#12]
观看视频的同时记录笔记。这个功能在logseq0.66失效

在视频下方记笔记时，视频会退回原来位置

![image](https://user-images.githubusercontent.com/7019907/164342884-6dbd5da2-9128-42c5-b411-d4a96d4865ac.png)

**Comment by sethyuan** [comment]
一个由renderer导致的问题，我已经找到解决方法并发布了新版本，请尝试。
