### ISSUE TITLE
插入B站视频显示无媒体

### ISSUE THREAD

**Issue by Ir0905** [sethyuan/logseq-plugin-media-ts#13]
感谢作者开发的插件。

我遇到的问题是，插入本地视频没有问题，但插入B站视频时就显示无媒体

![GIF 2022-4-21 17-55-30](https://user-images.githubusercontent.com/69003552/164430295-9e9ffcdf-d330-4eb0-9a13-9a5af20981f8.gif)

请问我的操作哪里出现问题了吗？

**Comment by sethyuan** [comment]
插入B站地址需要用Logseq自带的方法。

```
{{bilibili url}}
```

`url`部分是B站的URL。

**Comment by Ir0905** [comment]
> 插入B站地址需要用Logseq自带的方法。
> 
> ```
> {{bilibili url}}
> ```
> 
> `url`部分是B站的URL。

明白了，感谢回复。
