### ISSUE TITLE
{{renderer: media_controls}} does not activate timestamp feature

### ISSUE THREAD

**Issue by BruceSaltzman** [sethyuan/logseq-plugin-media-ts#14]
I discovered that I had to replace this command with {{renderer :media_controls}} to get it to initiate the feature. Just discovered the different colon placement that makes it work.

**Comment by sethyuan** [comment]
You must've been confused this plugin with another.

**Comment by BruceSaltzman** [comment]
OK, sorry.

------- Original Message -------
