### ISSUE TITLE
时间戳不渲染+渲染错误

### ISSUE THREAD

**Issue by fengchaobio** [sethyuan/logseq-plugin-media-ts#15]
## 出现问题
1. 只渲染一个时间戳，第二时间戳显示空白
2. 渲染出来的时间戳出现错误，显示为另外一个时间戳标注的时间

![Demo](https://user-images.githubusercontent.com/65841298/166099277-dcbf4f68-6787-40f0-b9fe-f941e7cd5730.gif)

**Comment by sethyuan** [comment]
是Logseq 升级到0.6.7之后导致的兼容性问题，我fix掉了。请尝试一下新版本。

**Comment by fengchaobio** [comment]
> 是Logseq 升级到0.6.7之后导致的兼容性问题，我fix掉了。请尝试一下新版本。

优秀！感谢
