### ISSUE TITLE
wmv video format support

### ISSUE THREAD

**Issue by ccyang2019** [sethyuan/logseq-plugin-media-ts#17]
Thanks for this convenient  plugin, it's very useful for me. 

But I found that it now not support local wmv file format.
Any plan to support "wmv" video file format in the future?

Thanks.

**Comment by sethyuan** [comment]
The underlying technology Logseq uses can not support wmv. I'd recommend you convert them to mp4 since they are more widely supported.

**Comment by ccyang2019** [comment]
OK. Got it. Thanks for your response.
