### ISSUE TITLE
Setting for adjusting time stamp placement time

### ISSUE THREAD

**Issue by wirtzdan** [sethyuan/logseq-plugin-media-ts#18]
Hi! I love and use this plugin on a regular basis. 

One thing I find myself doing a lot is going back in the player to make the Media Stamp and place the media stamp not after, but before what I want to capture. 

For me, it would be valuable to have a setting available, where I can enter a number of seconds (e.g "5" seconds), and then all time stamps I do are shifted five seconds before the actual spot where I create the time stamp. 

That way, I can keep on watching without needing to go back and replace the timestamp.

**Comment by sethyuan** [comment]
Glad you like it.

I added a setting called `captureOffset`, please give it a try. You may want to give it a negative value.

**Comment by wirtzdan** [comment]
Amazing. Thank you!
