### ISSUE TITLE
Link timestamp to specific video (similar to references)

### ISSUE THREAD

**Issue by 3699n** [sethyuan/logseq-plugin-media-ts#19]
At the moment, timestamps are not linked to / referencing a particular video. Timestamps always only refer to the current playing media renderer. This basically forces you to write notes underneath the video, to clearly indicate what video the timestamps refer to and so that the timestamp links work properly. Personally, however, I want content and ideas to structure my notes rather than the sources from which the content comes.

I want to be able to use timestamps as follows:

* Topic 1 _timestamp referencing vid 2_
* Topic 2
    * Subtopic 2a _timestamp referencing vid 1_
    * Subtopic 2b  _timestamp referencing vid 2_
    * Subtopic 2c _timestamp referencing vid 1_

Is it possible to have the timestamps reference a specific video, rather than the media player? 

This would be similar to how references currently work for PDF annotations: instead of referring to a page number of the PDF viewer, the reference refers to a page of a specific PDF.

**Comment by sethyuan** [comment]
Feature implemented, check the new version and the README file.

**Comment by 3699n** [comment]
Works Great! Thank you!

One feature that might be useful is to automatically insert the block ref of the video currently being played when using the keyboard shortcut or command to insert the timestamp.

**Comment by sethyuan** [comment]
About the recommendations:

1. I don't think inserting block ref should be the default behavior when inserting timestamps. Consider this scenario which most users employ, you put timestamps below the actual media, when you move the entire content to a new place, the block ref for the media actually changes, rendering all timestamps with a block ref invalid. The same doesn't happen for timestamps without a block ref, hence I think block refs should be added manually if wanted, not automatically.
2. Proposed solution: for timestamps with a block ref, I'll try to locate the media element if possible, if not, open the referenced block in the right sidebar and try to locate the media element there and start playing.

**Comment by sethyuan** [comment]
Above implemented in the new version released, please have a try.
