### ISSUE TITLE
【疑问】无法成功插入时间戳

### ISSUE THREAD

**Issue by mtuwei** [sethyuan/logseq-plugin-media-ts#2]
您好！

首先感谢开发这款能支持本地音视频的插件。在使用过程中遇到了如下图所示的问题，播放本地视频时，输入相关命令，按回车键后，似乎不能获取到时间戳。请问是否是因为我的操作有问题，谢谢解答！

![demo](https://user-images.githubusercontent.com/32591958/156622281-3aea8192-f882-4a42-b9d9-f1c018884de9.gif)

**【环境】：**
操作系统：Win10 21H1 x64
软件版本：V0.5.6

**Comment by sethyuan** [comment]
感谢反馈，我正在调查，感觉是Logseq插件加载机制和以前有点不一样导致的。

**Comment by sethyuan** [comment]
@mtuwei  我沟通了Logseq开发团队，他们做了调整，你可以卸载掉插件再从marketplace里重新安装下试试。

**Comment by mtuwei** [comment]
> @mtuwei 我沟通了Logseq开发团队，他们做了调整，你可以卸载掉插件再从marketplace里重新安装下试试。

可以了，再次谢谢！

**Comment by mtuwei** [comment]
@sethyuan ，这两天使用插件过程中产生了一个小问题，不知可否麻烦解答：
- 我应该如何设置，能够让生成的时间戳的默认样式为【{{renderer :media-timestamp, 00:01:00}}】

谢谢！

**Comment by sethyuan** [comment]
目前没有提供这种默认格式，有什么特别的理由指定到1分钟吗？

你其实可以将这一段复制下来，在需要的时候粘贴。

**Comment by sethyuan** [comment]
有啥特别理由吗？从秒到时分秒只是自己多写个：的区别。

**Comment by mtuwei** [comment]
> 有啥特别理由吗？从秒到时分秒只是自己多写个：的区别。
> […](#)
> 在 2022年3月11日，01:09，mtuwei ***@***.***> 写道： ﻿ 目前没有提供这种默认格式，有什么特别的理由指定到1分钟吗？ 你其实可以将这一段复制下来，在需要的时候粘贴。 抱歉，上面的表述引起歧义了😂，我的意思是希望能够将默认样式设置为【{{renderer :media-timestamp, 时:分:秒}}】。目前的默认样式为【{{renderer :media-timestamp, 秒}】. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

你好，是这样的，我这边视频会比较多，
- 对于较长的视频，我会添加比较多的时间戳，一个个修改的话，感觉有些重复劳动，也得计算秒和小时、分钟之间的转换😂
- 因为看到插件本身支持三种格式，只是默认格式为【秒】，所以想着可以在插件【设置】中修改默认格式为【时:分:秒】，类似添加【快捷方式】

谢谢你的耐心。

**Comment by sethyuan** [comment]
我没懂，你为什么要自己做时间的转换？插件不是每一种都支持的吗？你拿到的是秒你就直接写秒，拿到的是时分秒就直接写时分秒呀。

**Comment by sethyuan** [comment]
😂  所以我一直都很纳闷，你为什么非得要坚持自己写时分秒？！！
