### ISSUE TITLE
Can't get the timestamp shortcut to work

### ISSUE THREAD

**Issue by mujihuz** [sethyuan/logseq-plugin-media-ts#20]
Right only the onlly way that seems to work is using /Media timestamp
but no matter what I do (on mac), I can't get the shortcut keys to work.

**Comment by sethyuan** [comment]
Check the plugin settings:
![image](https://user-images.githubusercontent.com/3410293/190031754-7d24d544-ee8e-4c02-9585-f962d66b4837.png)

**Comment by mujihuz** [comment]
The settings were (and are now) as default: 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/86186715/190113077-07ec5f02-c81d-4801-aa26-e51559a50b77.png">

I have tried changing it to more complex or simpler combinations but it won't work.

**Comment by sethyuan** [comment]
How are you using the shortcut key may I ask? You should use it while typing, just like with the slash command.

Also, try restarting and/or uninstalling the plugin and reinstalling it again.

Lastly, `mod` in the above shortcut setting means `cmd` on macOS, just in case you used the wrong key.

**Comment by mujihuz** [comment]
I swear to 7 Gods that last night I tried and didn't work but now it works. Cheers mate for following up tho. You deserve lots of coffee :)
btw I'm having some issues with the text wrapper plugin. I'll just head over its repository page and ask you there. thanks a lot for your awesome plugins.
