### ISSUE TITLE
使用/insert插入的视频不能自动复制到assets文件夹里，换电脑视频就打不开

### ISSUE THREAD

**Issue by pipibaibai** [sethyuan/logseq-plugin-media-ts#23]
使用/insert + 视频的绝对地址 可以插入视频，也能正常播放，但是视频不能自动复制到assets文件夹里面。所以当我把文件夹所在的U盘在其他电脑的时候，视频就不能播放。
我录制的视频《logseq的media timestamp插件bug：使用/insert video 插入的视频能打开，但是不能复制到assets，换一台计算机，视频就打不开》：[https://www.bilibili.com/video/BV1414y1j7oX/?spm_id_from=333.999.0.0&vd_source=ffabafd567748fdd41a420b38a20c4ed](https://gitee.com/link?target=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1414y1j7oX%2F%3Fspm_id_from%3D333.999.0.0%26vd_source%3Dffabafd567748fdd41a420b38a20c4ed)

**Comment by sethyuan** [comment]
`/insert media` 不会帮你导入文件，因为视频一般都比较大，无论对用git做版本管理，还是用同步软件做同步都是挑战。

如果你想导入视频的话也很简单，README里第一个演示视频就有，建议看下。

**Comment by pipibaibai** [comment]
好的。
不过，README里第一个演示视频真的的是看不懂，尤其是其中几个右键菜单里的命令，在我的logseq里都找不到，都不知道这个命令是怎么出来的。能否把第一个演示视频的gif录个视频说明一下。

**Comment by sethyuan** [comment]
你往Logseq里拖拽一个视频，它就会被导入，但是Logseq默认给的内容不能以视频的方式显示，而是个链接。这个时候你右击前面那个点就会弹出块菜单，下面有插件提供的一个操作，可以将这个链接转换成能实现的视频。

**Comment by pipibaibai** [comment]
**第一步解决了，找到了“转换为媒体渲染”选项：**找到了logseq-plugin-media-ts v0.12.1版本右键菜单里没有“转换为媒体渲染”选项，我降低了版本，在v0.10.0版本里面右键菜单里有“转换为媒体渲染”选项。
**第二步没解决：右击前面那个点，选择“转换为媒体渲染”，链接没有转换为能显示的视频：**这个是什么原因？是logseq版本的原因吗？我试了logseq0.8.8  0.6.0  0.5.0都不行。视频演示链接：https://www.bilibili.com/video/BV1EP4y1S7iZ/?vd_source=ffabafd567748fdd41a420b38a20c4ed

**Comment by pipibaibai** [comment]
**第一步解决了，找到了“转换为媒体渲染”选项：**在logseq-plugin-media-ts v0.12.1版本右键菜单里没有“转换为媒体渲染”选项，我降低了版本，在v0.10.0版本里面右键菜单里有“转换为媒体渲染”选项。
**第二步没解决：右击前面那个点，选择“转换为媒体渲染”，链接没有转换为能显示的视频：**这个是什么原因？是logseq版本的原因吗？我试了logseq0.8.8 0.6.0 0.5.0都不行。视频演示链接：https://www.bilibili.com/video/BV1EP4y1S7iZ/?vd_source=ffabafd567748fdd41a420b38a20c4ed

**Comment by sethyuan** [comment]
@pipibaibai 我这边版本都是最新的，也都是好的，你开console（ctrl+shift+i）看看到底是什么问题。另外你是怎么安装的插件？通过插件市场吗？

**Comment by pipibaibai** [comment]
好的，我试一下。
我就装了logseq-plugin-media-ts这一个插件。

**Comment by pipibaibai** [comment]
哈哈，你的最后一问解决了问题：从插件市场安装了logseq-plugin-media-ts，就显示视频了。原来我从插件市场安装logseq-plugin-media-ts没成功，所以以后都是从你的github里下载了，手动安装的。

**Comment by pipibaibai** [comment]
麻烦您了，谢谢！！
其实，都是什么原因呢，就是因为logseq-plugin-media-ts是手动安装的（捂脸），切记得从插件市场安装。
捣鼓了好几天啊
