### ISSUE TITLE
 请问下是否可以添加一下类似Helium2.1.1插件的功能？

### ISSUE THREAD

**Issue by taogb2020** [sethyuan/logseq-plugin-media-ts#26]
如题，就是我在使用Media Timestampv0.12.1的时候，在视频下面做笔记，然后视频老是往上跑；能否考虑优化一下，像Helium2.1.1插件一样，让视频成为浮动的窗口在笔记的上方？
非常感谢您开发的插件！

**Comment by sethyuan** [comment]
为什么不结合Helium一起使用呢？
另外也可以将视频打开到右侧边栏。
