### ISSUE TITLE
支持加载字幕文件的功能

### ISSUE THREAD

**Issue by thomaszdxsn** [sethyuan/logseq-plugin-media-ts#27]
- [ ] [Adding captions and subtitles to HTML video - Developer guides | MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video)
- [ ] 可以自动将常见的 srt 字幕文件转换成 vtt 字幕文件，然后嵌入到 HTML

**Comment by sethyuan** [comment]
这个插件可能不适合做视频播放器相关的功能。也许将来有人做视频播放器的话你可以提给他看看。

**Comment by thomaszdxsn** [comment]
我可以为这个项目提 MR 吗？不过我要学习一下插件开发

**Comment by sethyuan** [comment]
当然，欢迎提PR！也欢迎点star收藏。
