### ISSUE TITLE
本地视频识别成音频的播放界面，点击播放后，有声音没画面。

### ISSUE THREAD

**Issue by X012C** [sethyuan/logseq-plugin-media-ts#28]
本地视频复制到logseq，点击视频渲染{{renderer :media, }}，代码变成了音频界面。是我操作不当的问题吗？
![image](https://user-images.githubusercontent.com/99554281/204287600-1b762296-a106-4de5-9d18-7266eeb1c6c1.png)

**Comment by sethyuan** [comment]
应该是你用了浏览器不支持的视频格式。建议转换成mp4

**Comment by X012C** [comment]
> 应该是你用了浏览器不支持的视频格式。建议转换成mp4

是放到了assets文件夹里的，mp4格式的。==

**Comment by X012C** [comment]
https://user-images.githubusercontent.com/99554281/204319340-67ad1662-52dc-417e-adbf-3f8639d9188b.mp4

1、视频文件名有[]时，似乎无法识别。
2、视频无法识别格式，调用了音频界面。

**Comment by sethyuan** [comment]
1. 你把markdown贴进去了，显然是错的。
2. 自行检查视频格式。Logseq是基于Chromium开发的，能放什么格式的视频是由Chromium决定的。
