### ISSUE TITLE
用哪个插件可以快速插入 mp4直链？

### ISSUE THREAD

**Issue by JiangLongLiu** [sethyuan/logseq-plugin-media-ts#3]
1. 我像把 mp4文件的加入到logseq，然后通过本插件插入时间戳，可行吗？
直链地址： https://alist.xhofe.top/d/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/01_%E5%A6%82%E4%BD%95%E4%B8%8A%E4%BC%A0%E7%85%A7%E7%89%87%E5%88%B0%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98.mp4

2. 请教快速插入直链MP4的插件是哪个啊？

**Comment by sethyuan** [comment]
也许我可以在本插件中提供这个/命令。

**Comment by sethyuan** [comment]
@JiangLongLiu 功能已实现，请尝试新版本。用`/insert video`和`/insert audio`就可以快速插入了，光标会落在需要粘贴URL的位置。

**Comment by hdg8087** [comment]
请问你的直链地址的那个网址，是做什么用的啊？是类似于视频图床吗？

**Comment by hdg8087** [comment]
> @JiangLongLiu 功能已实现，请尝试新版本。用`/insert video`和`/insert audio`就可以快速插入了，光标会落在需要粘贴URL的位置。

我在logseq上输入`/insert`，它跳出了 `/insert video`，然后我回车，然后节点上就什么都没有了。我如何插入视频的网址呢？

**Comment by JiangLongLiu** [comment]
> 请问你的直链地址的那个网址，是做什么用的啊？是类似于视频图床吗？

是一个私人网盘，你搜一下alist
