### ISSUE TITLE
/media timestamp 无法插入时间戳

### ISSUE THREAD

**Issue by fatekey** [sethyuan/logseq-plugin-media-ts#30]
输入 /media timestamp 后什么也没有出现，在同位置输入 {{renderer :media-timestamp, 00:01:00}} 可以正常使用
开发者模式报错为
```
Uncaught (in promise) TypeError: Cannot destructure property 'time' of '(intermediate value)' as it is undefined.
    at insertMediaTsRenderer (index.a37c0684.js:182:13)
```
操作系统为 macOS 
插件与 logseq 均为最新版

**Comment by sethyuan** [comment]
这个错应该是没有找到可抓取的多媒体导致的。待会儿我修一下代码，让它不抛错出来。

抓时间戳时要注意视频要处在时间戳的上方，或者sidebar中，不然会找不到视频。
