### ISSUE TITLE
怎么为Windows设置快捷键

### ISSUE THREAD

**Issue by bigbitbox** [sethyuan/logseq-plugin-media-ts#33]
作者你好
1. 我想请教怎么在Windows端设置该插件的快捷键
- 我试着修改配置文件 `ctrl + shift + e` 来表达，但它不起效果
2. 现在 `/Insert media` 是不是不能加载bilibili的视频了？
我用 `/Insert media` 不行 只能使用 `embed video URL` 才能正常加载，这和我无法使用快捷键有没有关系呢？
![](https://qncdn.cloudfalls.cloud/%E5%8A%A8%E7%94%BB.gif)

**Comment by sethyuan** [comment]
1. 你是用Windows的吧？试试这样设置快捷键： `mod+shift+e`。在Windows下mod就是ctrl，注意加号两边没有空格。
2. `/Insert media` 一直都不支持B站视频，就是要用 embed video url，这个和快捷键没关系。不过B站视频目前不支持自动抓时间，只能手写时间，时间戳可以帮你跳转。

**Comment by bigbitbox** [comment]
感谢回复
1. 我改成 `mod+shift+e` 在Windows上面也确实起效了。
2. _/Insert media 一直都不支持B站视频，就是要用 embed video url，这个和快捷键没关系。不过B站视频目前不支持自动抓时间，只能手写时间，时间戳可以帮你跳转。_   好的了解了❤
