### ISSUE TITLE
Default time settings?

### ISSUE THREAD

**Issue by kerim** [sethyuan/logseq-plugin-media-ts#34]
I see in the ReadMe you have written: "You can pass in "number of seconds", "minutes:seconds" or "hours:minutes:seconds"." Is this configurable? I see that I can do it manually, meaning that something like this works: `{{renderer :media-timestamp, 00:09:57}}` but when I use the insert timestamp command it always inserts something like this instead: `{{renderer :media-timestamp, 598.776742}}`. Is there some way that I can get it to always do the former? I don't need so much precision, and it the former (00:09:57) is the kind of time code I would use when sharing with other programs.

**Comment by sethyuan** [comment]
The time captured is in seconds. The easiest way I can think to copy the timestamp for sharing is via the Doc View Exporter plugin. You can enter a read-only mode using it, and the read-only mode will help you select to copy any content.

**Comment by kerim** [comment]
I guess that works well enough. Thanks.
