### ISSUE TITLE
插入本地视频，快捷键未生效

### ISSUE THREAD

**Issue by luckykellan** [sethyuan/logseq-plugin-media-ts#35]
环境：Mac
快捷键设置：
<img width="481" alt="image" src="https://github.com/sethyuan/logseq-plugin-media-ts/assets/109934256/fac35236-d47d-4855-a1de-335dfddb0c99">
现象：插入本地视频后，在下方无论怎么尝试都没反应
<img width="855" alt="image" src="https://github.com/sethyuan/logseq-plugin-media-ts/assets/109934256/7544be41-0645-434a-9be9-59e046a3cdd2">

**Comment by sethyuan** [comment]
设置好快捷键要重启下Logseq才能生效。我在我的mac上试过了，是mod+shift+t是可以的，对应是cmd+shift+t。

**Comment by luckykellan** [comment]
已解决，谢谢
