### ISSUE TITLE
Doesn't work with generic online MP4s

### ISSUE THREAD

**Issue by Victor239** [sethyuan/logseq-plugin-media-ts#36]
If you pick any random site, locate the MP4 file hosted on that site (e.g. `https://sp.rmbl.ws/s8/2/D/d/L/2/DdL2k.Faa.mp4` then try to use it with this plugin - then the timestamps won't work.

Please make it so that this plugin is compatible with MP4s from any website. Thanks!

**Comment by sethyuan** [comment]
I ran some tests. You probably used `/Embed video URL`, it wrongly inserts the video (it inserts it as an iframe instead of a video). Try use a markdown link like this: `![](https://sp.rmbl.ws/s8/2/D/d/L/2/DdL2k.Faa.mp4)`

**Comment by Victor239** [comment]
Ah you're right, that works. Thanks! 

I find that the videos embedded using Markdown are center-aligned rather than left-aligned but I guess that's just a upstream issue as well. 

Cheers for this plugin.
