### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by L2590432546** [sethyuan/logseq-plugin-media-ts#37]
当插入内存较大（例如超过100M）的视频时无法播放

**Comment by sethyuan** [comment]
两个方面：

1. 视频的播放其实是发生在底层的，不是插件的功能，所以播放不了插件无法解决。
2. 按说不应该播放不了，你检查下会不会是视频格式的问题，例如mov, mkv等应该都是底层不支持的。具体的可以查下Electron对视频格式的支持。
