### ISSUE TITLE
【参考】自动获取B站视频当前位置，以及点击时间戳实现直接定位

### ISSUE THREAD

**Issue by mtuwei** [sethyuan/logseq-plugin-media-ts#4]
开发者，你好！

关于【B 站视频，出于 Logseq 本身的一些安全性限制，无法获取当前位置，点击时间戳跳转时也不能直接定位，需要重新加载播放器】的问题，下面是@boninall提供的一种可能解决方案，希望能有帮助，仅供参考，谢谢！

> 那个开了个反向代理，麻烦点，可以把这个链接发给开发者来参考代码 https://github.com/aidenlx/mx-bili-plugin

![image](https://user-images.githubusercontent.com/32591958/156876315-c7bae5d8-b49a-4b44-aa32-ed4a1a9f949b.png)

**Comment by hdg8087** [comment]
搭个车，请问一下：我在log上写入以下内容，为什么log上没有视频出来呀？
视频名叫  A01 初识PS.mp4  在D盘的文件夹1下面。
<video controls scr="file://D:\1\A01 初识PS.mp4"></video>

**Comment by hdg8087** [comment]
搭个车，请问一下：我在log上写入以下内容，为什么log上没有视频出来呀？
视频名叫 A01 初识PS.mp4 在D盘的文件夹1下面。
![image](https://user-images.githubusercontent.com/71086865/156877426-962ecff5-c66a-45ac-892f-017e16db5346.png)
![image](https://user-images.githubusercontent.com/71086865/156877431-b2da0bd9-0d87-4a0e-aab4-2ca0a65bf150.png)

**Comment by hdg8087** [comment]
另外，能不能像ob的时间戳插件那样，把音视频，单独另开一个页面，而不在笔记中显示？

目前当然很好，但缺点是：

你一般不会把视频放在页面的第1层节点上，对吧？那就假如放在第2层。
然后时间戳要打在第3层节点上，
然后笔记做在第4级节点上（我不知道时间戳是不是一定要单独占一行）

这样的话，笔记至少要从第三层开始，受大纲的限制，笔记可用空间就很小了呀。

如果把音视频另开一个界面，则笔记可以从第一层开始写，就好多了。

**Comment by sethyuan** [comment]
@mtuwei 这个OB的插件我之前有稍微了解过，不过这种方式需要的权限更大，Logseq是不允许的。其实如果Logseq安全设置能放开的话不需要这么麻烦，还会有更好更方便的解决方案，但我估计没办法因为这个需求就说服开发团队放弃安全设置。

**Comment by sethyuan** [comment]
@hdg8087 Windows下路径要这样的格式写：`file://C:/Users/A/movie.mp4`，空格要escape，或者简单点，不要有空格。一句话，要是合法的URI。

关于打开在侧边栏我应该已经在你的另一个线程中回答过了，可以参看README中的动图。

**Comment by hdg8087** [comment]
如果实在路径中有空格怎么办呢？

**Comment by sethyuan** [comment]
@hdg8087 我刚更新了一版，如果你拷贝了完整的视频文件路径到剪切板的话，在插入媒体时插件会自动帮你处理为正确的URI格式。你试试看。

**Comment by sethyuan** [comment]
@hdg8087 BTW，视频应该也可以开启画中画模式，也可以用来边看边做记录。

**Comment by wrwe3888** [comment]
感谢开发者。我也同时在使用ob的时间戳插件，感觉就使用流程来说，ob的插件稍顺手些。比如前面那位哥们说的 笔记至少要从第三层开始。。。。。不知道开发者能不能再把展现方式修改一下。十分感谢！

**Comment by mtuwei** [comment]
> 感谢开发者。我也同时在使用ob的时间戳插件，感觉就使用流程来说，ob的插件稍顺手些。比如前面那位哥们说的 笔记至少要从第三层开始。。。。。不知道开发者能不能再把展现方式修改一下。十分感谢！

应该是不存在这种层次要求的，我使用过程中给没有出现这个问题

**Comment by wrwe3888** [comment]
哦哦，不太懂你说 应该是不存在这种层次要求的 是什么意思。
那你做的视频笔记，都是从logseq的第几个层级开始记笔记啊？
是直接从第1层级开始，还是从第3、第4层级开始啊？

**Comment by li-chena** [comment]
> 

你可以把笔记所在的块在右侧栏打开，或者把视频在右侧栏打开，这样就不存在记笔记不方便的情况了

**Comment by mtuwei** [comment]
> @mtuwei 这个OB的插件我之前有稍微了解过，不过这种方式需要的权限更大，Logseq是不允许的。其实如果Logseq安全设置能放开的话不需要这么麻烦，还会有更好更方便的解决方案，但我估计没办法因为这个需求就说服开发团队放弃安全设置。
> 
> 另外还有一种方法是联系到B站开发团队，让他们实现跨iframe的通讯，目前他们应该是没有正确实现（或者根本就没有实现的）。油管是实现了的，所以Logseq中油管视频的时间戳是能拿到时间的。

了解了，谢谢回复！

**Comment by mtuwei** [comment]
> 哦哦，不太懂你说 应该是不存在这种层次要求的 是什么意思。 那你做的视频笔记，都是从logseq的第几个层级开始记笔记啊？ 是直接从第1层级开始，还是从第3、第4层级开始啊？

我这里是都可以的
