### ISSUE TITLE
Couldn't handle commas «,» in pathname

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-media-ts#40]
## Demo:
<img width="600px" src="https://github.com/sethyuan/logseq-plugin-media-ts/assets/1984175/232d469e-5148-442b-bf50-9b463cedc33e"/>

### Expected behaviour
Quotes <code>""</code> could help handle this.

**Comment by sethyuan** [comment]
It is recommended to use the standard markdown syntax for media inclusion now. Like this: `![](/Users/path/media.mp3)`. Please give it a try.

**Comment by stdword** [comment]
Yeah! That way is worked!
