### ISSUE TITLE
插件能否在导出发布页面 同样有效？

### ISSUE THREAD

**Issue by JiangLongLiu** [sethyuan/logseq-plugin-media-ts#5]
##  从导出页面到nginx
![导出页面](https://user-images.githubusercontent.com/7019907/157575488-c3d81dc8-01f7-4087-99ac-66860e1a67e4.png)
## 通过nginx浏览导出的页面
![视频时间戳_nginx发布页面](https://user-images.githubusercontent.com/7019907/157575489-50a4195f-4ef0-4593-ace9-06ffd9ce28ef.png)

**Comment by sethyuan** [comment]
这个受Logseq本身发布的限制，如果Logseq的发布功能不支持插件的话，那么作为插件自身是无能为力的。

**Comment by JiangLongLiu** [comment]
> Logseq

好的，我给logseq提了一个issue[ 4522](https://github.com/logseq/logseq/issues/4522)
