### ISSUE TITLE
可否录个简单的视频讲一下？目前的说明写的有点抽象啊。

### ISSUE THREAD

**Issue by hdg8087** [sethyuan/logseq-plugin-media-ts#6]
比如，我连本地的视频文件都插不到 logseq 里面去。
如下动图1。我一回车，/insert video就没有了，我到哪里插入视频呢？
按你动图上的格式写，也插入不了视频。
你的动图不是视频，没法暂停。真让人抓狂！

更不谈左边做笔记、右边打开视频。
![GIF](https://user-images.githubusercontent.com/71086865/157709978-dfdb0960-38f9-4ec0-b2a8-dc5792169ac6.gif)

**Comment by sethyuan** [comment]
不应该是这样，你可以尝试重启Logseq。另外能描述下你的使用环境和软件版本吗？建议用最新的版本。

**Comment by sethyuan** [comment]
我想起来了，你卸载插件，重新安装一下试试。这是之前插件上架的时候marketplace没有给我设置对模式导致的，后来我联系了开发团队他们帮我重新做了调整，但是需要卸载重装。

另外关于视频插入，操作方式是：

1. 拷贝视频完整地址
2. 在Logseq中键入 /insert video

它会自动插入并处理剪切板中的地址。

**Comment by hdg8087** [comment]
0.63 + 0.42
已卸载插件、重启logseq很多遍
视频地址是完整的（包括路径和文件名本身，含扩展名）
在在Logseq中键入了 /insert video

结果仍然如上

**Comment by hdg8087** [comment]
win10

**Comment by sethyuan** [comment]
我这里没法重现，要不你开启开发者模式，把可能出错的日志截个图我看看。操作方法：

![image](https://user-images.githubusercontent.com/3410293/157782197-8912d876-7b7f-46c8-b2d2-06f261965bfb.png)

按`ctrl+shift+i`打开开发者工具，切换到`Console`，清掉里面的内容，执行插入操作。

![image](https://user-images.githubusercontent.com/3410293/157782315-b8a07b14-1c44-457e-a4fe-e4a673e09b5f.png)

将错误截图。
