### ISSUE TITLE
Error shows up whenever I open Logseq

### ISSUE THREAD

**Issue by CharlesChiuGit** [sethyuan/logseq-plugin-media-ts#7]
Hi, this error always shows up whenever I opened Logseq?
![image](https://user-images.githubusercontent.com/32497323/160535429-9eede3ae-0dbc-443e-a6bb-e6ed5db5a84b.png)
How can I fix it? Thx!

**Comment by sethyuan** [comment]
I'm seeing this on my Windows too, I think it's somehow related to Logseq versions, but I can't tell where exactly is the problem. You can try remove the plugin and upgrade Logseq to the newest version (0.6.5), and then reinstall the plugin.

For my specific case, I even had to re-index my graph. 😅

**Comment by CharlesChiuGit** [comment]
hmmm, I already upgraded to 0.6.5. So I tried to re-install the plugin and re-index, but the error still appears. Will this error effects the usage of the plugin?

**Comment by sethyuan** [comment]
Can you check if the plugin's settings file is corrupted, it should look something like this:

```json
{
  "mediaTsShortcut": "mod+shift+m",
  "disabled": false
}
```

**Comment by sethyuan** [comment]
As the last resort, you can go to Logseq's settings and perform a cache clear.

![image](https://user-images.githubusercontent.com/3410293/160547501-da114c53-827c-40c9-8e12-dd9875b83795.png)

**Comment by CharlesChiuGit** [comment]
Wow, the json file is indeed corrupted! Mine looks this:
![image](https://user-images.githubusercontent.com/32497323/160551570-45b40fa0-3e1d-44a9-8f7d-760349edb7dc.png)

After pasting the shortcut, the error is gone forever! Thx for your help!
