### ISSUE TITLE
在线视频无法进行时间戳记录

### ISSUE THREAD

**Issue by Fluoxetine-int** [sethyuan/logseq-plugin-media-ts#9]
十分感谢大佬写出插件，本地视频能够成功记录！但是我在进行YouTube视频复制网址再 ‘/insert video' 不能成功读取导入。尝试用嵌入视频的方法放进Logseq之后，时间戳无法对当前在线视频进行记录

https://user-images.githubusercontent.com/60655208/163507598-ee9284f4-0142-416a-b6c2-bbf5b3458086.mp4

https://user-images.githubusercontent.com/60655208/163507608-95c41c39-1f4a-4ce8-a7d5-55d2055c881b.mp4

**Comment by sethyuan** [comment]
我没有做对Youtube的支持，因为Logseq自带的就有。

<img width="341" alt="image" src="https://user-images.githubusercontent.com/3410293/163510925-96798ba4-b27e-49f5-b641-f3bf9022ab43.png">

针对Youtube你用Logseq自带的就可以了。

**Comment by Fluoxetine-int** [comment]
好哒，之前没注意到，谢谢哈！
